### PR TITLE
Remove last digits of IP in server logging (default)

### PR DESCRIPTION
**Pull request by ann0see**
My proposal in https://github.com/corrados/jamulus/issues/576#issuecomment-687860878
To be discussed.

### CODE REVIEW

**Comment by pljones** [comment]
Sorry, I strongly object to having this information removed.  If I'm providing a public service and someone chooses to use it, they choose to expose their IP address.

**Comment by pljones** [comment]
It's also a potential security flaw, as it anonymises clients, enabling DDoS attacks more easily.

I can't see that it provides any benefits at all.

**Comment by atsampson** [comment]
I also don't think this is a good idea - it's not effective anonymisation, and it just makes the server operator's life harder. Better to document that the logs contain addresses and you should treat them like logs from any other server, i.e. use something like logrotate to manage retention.

**Comment by ann0see** [comment]
What does @corrados think? Should it be closed or should the default behavior be changed to "show full IPs in log except if server is started with e.g. —anonymizeip“?

**Comment by corrados** [comment]
I actually agree with the others. I think the IP address is an essential part of the server operation. If a user does not want to see and log any IP address, he can run the server headless with std-out piped to the null device and do not use the logging feature.

**Comment by ann0see** [comment]
Ok. If you think that’s ok I‘ll close the PR

**Pull request closed without merging**
