### PR TITLE
Update bandwidth requirements

### PR DESCRIPTION
**Pull request by gilgongo**
To match those on wiki.

### CODE REVIEW

**Comment by corrados** [comment]
Why do we need at least 600 kbps?

**Comment by corrados** [comment]
grafik

**Comment by gilgongo** [comment]
Oh, sorry, I was just using the wording that came from the discussion on bandwidth #64 with @vocobox (I later moved his wording to separate places on the wiki)

https://github.com/corrados/jamulus/wiki/Quality,-delay-and-network-bandwidth/_compare/41bcae58ccc34021ceeff3dca7b4170b18f2c148...039f769274edf47fec0b934fe4c145c9639b5443

**Comment by corrados** [comment]
Ok, so shall I close this pull request without merging?

**Comment by gilgongo** [comment]
I;m not sure why it ended up as 600. I'll see if I can check with Vocobox - close the PR and I can do it later once we've got some clarity.

**Pull request closed without merging**
