### PR TITLE
Sagora1.1

### PR DESCRIPTION
**Pull request by sagora-repositorios**

### CODE REVIEW

**Comment by pljones** [comment]
Pull corrados:master and rebase your branch, resolving the conflicts.  It's currently many versions behind.

**Comment by corrados** [comment]
Hi sagora-repositorios. Is this pull request a result of the discussion in the Jamulus forums: https://sourceforge.net/p/llcon/discussion/533517/thread/a17b6db848?

**Comment by tormodvolden** [comment]
It was probably not meant to be a merge request. However it shows that they are rebasing their code on top of the jamulus git repo, which is good.

**Comment by corrados** [comment]
@sagora-repositorios I assume that you wanted to create a fork which contains all the Jamulus original version history which is good. That's the way it is supposed to be. In the Git history of your fork one can easily see what is the original Jamulus code and what are your modifications/contributions. But I would like to recommend the following:

It seems you have based your fork on a recent version of Jamulus but have overwritten all the code in that fork by your current code which is based on an older version of Jamulus. You should instead base your fork an exactly the same version you based your Sagora code on when you started your modifications. If you do that, you can easily see all the changes you have done.

**Comment by corrados** [comment]
The Sagora modifications should be on the Sagora fork and should not be merged in the Jamulus code, therefore I will close this pull request now.

**Pull request closed without merging**
