### PR TITLE
Debian packaging improvements

### PR DESCRIPTION
**Pull request by tormodvolden**
- Build binary on "any" architecture
- Binary depends on adduser
- Improve postinst script

Signed-off-by: Tormod Volden <debian.tormod@gmail.com>

### CODE REVIEW

**Comment by corrados** [comment]
@braindef and @mirabilos, can anyone of you please review these changes? Thanks.

**Comment by mirabilos** [comment]
From a Debian PoV, I’d not use `--quiet` for `adduser`, but looks okay.

**Comment by tormodvolden** [comment]
Yeah, I have just seen --quiet been used in many official packages. And the message that shows up on upgrade or reinstall saying "Exiting" is a bit annoying.

**Comment by mirabilos** [comment]
Tormod Volden dixit:

>the message that shows up on upgrade or reinstall saying "Exiting" is a
>bit annoying.

OK, agreed, keep it in.

**Comment by corrados** [comment]
Thank you guys. I'll merge it now.

**Pull request merged**
