### PR TITLE
show number of connected clients as well as max clients in serverbrowser

### LINKED ISSUE #451: Maximum clients on server not visible in serverlist
Hi,
I'd love to see how many channels a server offers in the serverlist.
When people want to meet in a bigger group they should be able to see which server is going to fit their needs. At the moment they have to do it by trial and error. I commited some code into my branch to fix this issue. Was it ok to create a pull request? (Sorry for asking, this is my first time ;)
cheers, nils

### PR DESCRIPTION
**Pull request by dingodoppelt**
Fixes #451

### CODE REVIEW

**Comment by corrados** [comment]
Thanks. Do you want to be listed in the About dialog of the Jamulus software under Contributors?

**Comment by dingodoppelt** [comment]
thanks for pulling :) you made me very happy, if you want you can add me to the contributors. It would be an honor for me :)

**Comment by corrados** [comment]
Sure :-)
https://github.com/corrados/jamulus/blob/master/src/util.cpp#L463
Just tell me if you would like to see your real name in the list.

**Comment by dingodoppelt** [comment]
Yes please, it is Nils Brederlow

**Comment by corrados** [comment]
Done: https://github.com/corrados/jamulus/blob/master/src/util.cpp#L463

**Comment by dingodoppelt** [comment]
thanks :)

**Pull request merged**
