### PR TITLE
Remember if user selected the desktop icon on last install

### PR DESCRIPTION
**Pull request by ann0see**
@pljones 

The installer now remembers if you selected/didn't select the creation of a desktop icon.

Do we also need to remember if the user selected to run the app or skipped the ASIO check?

### CODE REVIEW

**Comment by ann0see** [comment]
This should be tested by corrados and pjones before we merge it.

**Comment by corrados** [comment]
Let's merge it. You have done so many changes to the installer. After everything is ready, we have to do a lot of testing anyway.

**Comment by corrados** [comment]
I just saw the following: You have changed the following files:
 src/res/jamulus-icon-uninstall-2020.psd 
windows/uninstaller-welcome.bmp 
windows/uninsticon.ico

Was this indended? Do you overwrite the files from GeheimerEichkater? Maybe this is a merge issue. Please check.

**Comment by ann0see** [comment]
Yes. This is intended. Sorry I forgot to mention this: since the installer and uninstaller both use the same images, I removed the duplicate uninstall welcome icon and tell the installer to use the same one for uninstalling. Also since the uninst icon doesn't get shown, I removed it.

**Pull request merged**
