### PR TITLE
Get rid of a warning

### PR DESCRIPTION
**Pull request by pljones**
QtCreator was annoying me with its little yellow markers...

### CODE REVIEW

**Comment by corrados** [comment]
Wouldn't it be sufficient to do:
`void CServer::OnTimer()
{
    int                i, j, iUnused;
    int                iClientFrameSizeSamples = 0;`

**Comment by pljones** [comment]
Oh... well, could do - I just felt this was more explicit about when the value is being "unused".  There are four places it's currently set and two places it's currently not set.  So you could (potentially) end up setting it in the first if and then not clearing it in the second (okay, we can see it's not used... but you have to look carefully for what the nullptr pointer value is used for).

**Comment by corrados** [comment]
Yes, but just to remove the warning, I like my simple solution a bit better :-).

**Comment by corrados** [comment]
I just fixed it myself with my last commit. So no need for a merge.

**Pull request closed without merging**
