### PR TITLE
Feature/315 audacity lof

### PR DESCRIPTION
**Pull request by pljones**
#315 - provide a "List of file" for Audacity representing the track items.

Based off my #295.

### CODE REVIEW

**Comment by corrados** [comment]
In this pull request there are so many things included from the other pull requests.
Let's do things step-by-step. First we should fix the first pull request, then merge this. Then the next and so on. So I will give you feedback on this one as soon as the others are merged.

**Comment by pljones** [comment]
Bumped as it can go in off master without waiting for the other two PRs.

**Comment by corrados** [comment]
Great, thanks. Could you please also update the ChangeLog?

**Comment by corrados** [comment]
BTW: Just to let you know: In files which are "yours", i.e. you have introduced them and it is a special functionality which is not critical for Jamulus operation, I will not do a code review as I do for the other files. But I guess you have already found that out yourself ;-).

**Comment by pljones** [comment]
Done :)

**Comment by corrados** [comment]
I just did some Qt4 -> Qt5 changes. I'll apply them now and hope that I do not break your pull request (but should not). Then I'll merge this one.

**Pull request merged**
