### PR TITLE
Change link

### PR DESCRIPTION
**Pull request by gilgongo**
To avoid confusion as per https://github.com/corrados/jamulus/issues/238

### CODE REVIEW

**Comment by corrados** [comment]
Dies this means that the Help menu links oft the release Version 3.5.3 will no longer work?

**Comment by gilgongo** [comment]
Should still work because 3.5.3 will be pointing at a copy of the "Getting Started" page [here](https://github.com/corrados/jamulus/wiki/Software-Manual).

**Comment by corrados** [comment]
That is not good. Links in older versions should work for a long time, otherwise it is useless to implement links in the software at all. But now we have a problem that we do not have single source anymore if we keep the old page.

**Comment by gilgongo** [comment]
Unfortunately, the Github wiki doesn't let you change the H1/title without altering the URL. Although I didn't mean we'd delete the old page **immediately** once 3.5.4 is out, it's a good point about the older versions. Maybe it's blessing in disguise: for anyone hitting the old page, we can show them a message encouraging them to upgrade :-)

**Comment by trebmuh** [comment]
What about leaving a link pointing to the new wiki page in the old wiki page?

**Comment by gilgongo** [comment]
@trebmuh That's what I'm doing, yes.

**Pull request merged**
