### PR TITLE
Add flatpak build support, with CI

### PR DESCRIPTION
**Pull request by ranfdev**
Warning: I can say it compiles and runs, but I don't have jack installed and my sound card isn't working, so I can't test anything.
Before this PR gets accepted, someone should test this.

To manually build the flatpak release, you can run
```
flatpak-builder build distributions/io.jamulus.Jamulus.json --force-clean --install --user
```

Then Jamulus should show up in your app list.
If you want to launch it from the terminal

```
flatpak run io.jamulus.Jamulus
```

This solves #803 
Enjoy

### CODE REVIEW

**Comment by ann0see** [comment]
Great. Does this upload the build anywhere?

**Comment by ranfdev** [comment]
Yes, you can find the build artifact when viewing the github action

**Comment by ann0see** [comment]
Ok. But you can't download it after the build artifact is deleted? We might need to make modifications to this file:

https://github.com/corrados/jamulus/blob/master/.github/workflows/autobuild_deb.yml

to allow automatic upload to a release.

**Comment by ann0see** [comment]
I haven’t tested it. So probably this is untested code.

**Comment by corrados** [comment]
Does it make sense to merge it anyway? As far as I understood, if I apply a release tag, everything works automtically, right?

**Comment by ann0see** [comment]
>  As far as I understood, if I apply a release tag, everything works automtically, right?

Yes. Everything will run in GH actions and you can have a look at it in the actions tab.

**Comment by corrados** [comment]
Good that you mention that. Github Actions are currently disabled for the corrados/jamulus repo. Do you have it set to "Allow all actions" in your repo?

**Comment by ann0see** [comment]
No. Actually I think it was already enabled for me.

**Comment by corrados** [comment]
Ok, Github Actions are now enabled. Since this Pull Request is just about adding an additional action which may or may not work but does not break anything existing, I'll apply this now and when the next release is done, we see if it worked or not. If it not worked, then we can fix the issue for the upcoming Jamulus version.

**Comment by ann0see** [comment]
Ok. I could only speak for my action. 

Have a look at this: https://github.community/t/workflow-error-action-not-allowed/16788/4

since the workflow seems to fail.

**Pull request merged**
