### PR TITLE
#555 Interaction between command line and inifile

### PR DESCRIPTION
**Pull request by pljones**
These changes are based on the discussion in #555 and make what I believe was stated as the target implementation effective.

### CODE REVIEW

**Comment by corrados** [comment]
I think the goal you try to reach is to have consistency. But your changes break a use case: Running Jamulus headless on a Raspberry Pi zero: https://github.com/corrados/jamulus/blob/master/distributions/raspijamulus.sh#L111 As you can see, I am using the inifile for the client.

So what I wrote in #555 means, that for the server we have the situation that in headless mode the inifile is never used. But the situation is different for the client. For the client I need the possibility to use the inifile even in headless mode. That is the reason the code is implemented as it is in the current Git master. So that is on purpose, actually.

The other thing is that we should keep the support of all command line arguments which we have in normal mode also for the headless mode. There was a discussion going on when the HEADLESS compile mode was introduced. I was also wanting to remove command line arguments for the headless mode but the develooper of the HEADLESS compilation convinced me that it is better to keep the complete set of command line arguments but just show a warning (as you get if you compiled Jamulus with HEADLESS but do not use the -n command line argument, then you get: "No GUI support compiled. Running in headless mode.".

**Comment by corrados** [comment]
I have just added more description to the help text: https://github.com/corrados/jamulus/commit/8b7ccde7d64f739e96fa0b6415b6840eb5eda3f3

And also a warning if the inifile is used in headless server mode: https://github.com/corrados/jamulus/commit/0a0f21d90c4f248de237a763b2c03c264e54ad06

**Comment by pljones** [comment]
It sounds like there's something missing from the command line for the RPi usecase.  Having to edit the ini file by hand sounds far from ideal, compared with passing command line options.

**Comment by corrados** [comment]
This script is a special case since I want to support the Pi Zero and also better performing Raspberry Pi versions as well. The recommended way of doing it is to start the client with a GUI and using the --inifile (to specify the file you want to use for the Raspberry Pi), change all the settings you want and exit the client. Then you have everything stored in that ini file which you can then use for your headless Jamulus client on the Raspberry Pi.

**Comment by pljones** [comment]
>  The recommended way of doing it is to start the client with a GUI and using the --inifile

That would work for the server, too, of course, if it was allowed to load the inifile when headless.

**Pull request closed without merging**
