### PR TITLE
Added code to log disconnection of users

### PR DESCRIPTION
**Pull request by storeilly**
Straightforward logging for disconnected users. Issue # 277

### CODE REVIEW

**Comment by storeilly** [comment]
I missed something stupid, it's logging multiple times on unix. Reviewing....

**Comment by atsampson** [comment]
The client can send multiple `PROTMESSID_CLM_DISCONNECTION` messages, since it'll do so whenever it gets a packet from the server it's not expecting. Guard the call to `AddDisconnected` with `if ( vecChannels[iCurChanID].IsConnected() )`?

(At the moment this'll only log when a client tells the server it's disconnecting; do you also want to log disconnections resulting from timeouts?)

**Comment by corrados** [comment]
See my comment in the Issue regarding this pull request: https://github.com/corrados/jamulus/issues/277#issuecomment-651162973

**Comment by corrados** [comment]
Since https://github.com/corrados/jamulus/issues/277 is closed, shouldn't we close this pull request as well?

**Comment by storeilly** [comment]
Thanks Volker

**Pull request closed without merging**
