### PR TITLE
Starting French translation #77

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by corrados** [comment]
Thank you.

**Comment by trebmuh** [comment]
@corrados thanks for the merge. If I build from master head, can I expect those strings to be translated in French in the GUI?

**Comment by corrados** [comment]
Since the translation is still in experimental state, you have to start Jamulus with the "--translation" command line argument to see your translations. Please give me feedback if it worked for you.

**Comment by trebmuh** [comment]
@corrados : OK, just tested and that works flawlessly.
I'll be updating the French translation on the coming days now.

**Comment by corrados** [comment]
Thanks for testing. Please wait some days before you continue the translation because I want to clean up some strings in the code to make the translation easier.

**Comment by trebmuh** [comment]
OK

**Comment by trebmuh** [comment]
OK, waiting for you ping then.

**Comment by trebmuh** [comment]
OK, waiting for you ping then.

@corrados BTW, are the new translated strings (*.qm) calculated at build time? If so, I could check that I didn't made any mistake before making a PR next time (like the double "<" on my previous PR).

**Comment by corrados** [comment]
The *.qm files are generated with the Qt "lrelease" tool. I run that tool manually before I compile the code.

**Comment by trebmuh** [comment]
OK, thanks.

**Comment by corrados** [comment]
Ok, clean up finished. You can continue if you like.

**Comment by trebmuh** [comment]
Nice, I'll do that ton tomorrow.

**Pull request merged**
