### PR TITLE
Multiple frame sizes in recorder

### PR DESCRIPTION
**Pull request by pljones**
OK, after going off in the wrong direction, here's my second attempt :).

Nice and simple.  Tell the recorder the frame size when it's decided.

As far as I can tell, it's handling server frames, so it's fine to do that just the once.  (I'd started thinking it was handling client frames -- but they've already been pre-processed.)

I've tested with an old client and this new version run with and without -F and the recording worked okay.

### CODE REVIEW

**Comment by corrados** [comment]
Great, you are extremely quick.
Since it is all your code I'll merge it without a code review.
What about these: https://github.com/corrados/jamulus/issues/30 and https://github.com/corrados/jamulus/issues/35? Are these real issues to be addressed?

**Comment by pljones** [comment]
#30 - yes it core dumps.  The choice between JPEG (which will fail with `-n`) and SVG is made based on filename (`CServerLogging::EnableHistory`).  Bit of a hack... :)

#35 - I'm almost certain it's a set up problem.  If you run the server twice with -R, first time it'll create the directory if it's not there, second time it'll happily not create the directory.  If it's can't "see" the directory, due to permissions issues, it's likely not to be able to create it either.

**Comment by corrados** [comment]
OK, I saw your comments in the Github Issues. Thanks for taking care.
There is another issue reported in the forum which relates to your code: https://sourceforge.net/p/llcon/discussion/server/thread/2d5a42c1fe/. I assume that shortly there will also be an issue created for it at Github.

**Comment by sehe** [comment]
@pljones Thanks for this work, it improved a few things I had already drafted up (e.g. CurOpusDecoder and the many different calls to `opus_custom_decode`).

I have one question about the -F server option (to put the server in 64 byte frame mode). When is this feature handy? I'm assuming it will be 100% compatible with 128b-frame clients? So, am I right in thinking that this merely helps tune the server-side latency in more precise steps by selecting a more fine-grained jitter buffer size?

**Comment by corrados** [comment]
Yes, correct.

**Pull request merged**
