### PR TITLE
Update to Portuguese Translation

### PR DESCRIPTION
**Pull request by Snayler**
Not sure why this shows as conflicting files

### CODE REVIEW

**Comment by corrados** [comment]
Thank you for the update. Unfortunately, we have conflicts with the Git master branch. Can you please merge from the master to avoid the merge problems?

**Comment by Snayler** [comment]
I'm not sure how to do that. I forked the latest version and uploaded the files on my fork. I can't upload files on your repository as I don't have push access.

**Comment by corrados** [comment]
Ok, I just tried to fix the merge conflict. I hope that it worked correctly.

**Comment by Snayler** [comment]
Can you tell me why this conflict happened? Was it because of the .qm file?

**Comment by corrados** [comment]
I guess it was caused by my latest change in the code. Today I did apply some modifications to the Git code which was done in parallel to your changes.

**Comment by corrados** [comment]
Anyway, the merge seems to have succeed as far as I can tell. Thanks.

**Pull request merged**
