### PR TITLE
Automatically build Debian packages and set latest tag to release

### PR DESCRIPTION
**Pull request by ann0see**
#795 

This will make the release process slightly different (mainly the latest tag will be set automatically).

If somebody adds a tag with r and pushes it to the repo, GitHub actions will compile the .deb files from the latest code and upload it to a release: https://github.com/ann0see/jamulus/releases/tag/latest

Hacks/Bugs:

I currently compile Jamulus on Ubuntu 18.04 but use the 16.04 dependencies. This seems to allow us to have the pan function on Debian 10 but doesn't show the muted icon in the main mixer. Hopefully it doesn't break anything else

### CODE REVIEW

**Comment by corrados** [comment]
Does this mean that everytime I set a new label (i.e. any label), the "latest" tag will be moved and a release will be created? This is not intended since sometimes I apply some labels to some intermediate states of the code. I do not want the "release" label to point to that tag.
How can we solve this?

**Comment by corrados** [comment]
I just saw that you already filter the tags by "r*". So I only have to make sure that the inofficial tags do not start with an "r", right?

**Comment by corrados** [comment]
> This will make the release process slightly different (mainly the latest tag will be set automatically).

So you mean that instead of tagging the repo and afterwards move the latest tag -> now I only set the release tag and the movement of the latest tag is done automatically? So it means that I have less work to do (which would be good :-) ).

**Comment by ann0see** [comment]
> So I only have to make sure that the inofficial tags do not start with an "r", right?

Yes. That's the case

> So you mean that instead of tagging the repo and afterwards move the latest tag -> now I only set the release tag and the movement of the latest tag is done automatically? So it means that I have less work to do (which would be good :-) ).

Yes.

**Comment by ann0see** [comment]
In theory macOS and Windows builds could be possible with GH actions too. But I haven't managed it yet (and would like to focus on one OS first)

**Comment by corrados** [comment]
Great, thanks.

**Comment by corrados** [comment]
> In theory macOS and Windows builds could be possible with GH actions too.

If you could figure out how to do it, that would be great.

**Pull request merged**
