### PR TITLE
Fix some typos (found by codespell)

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by corrados** [comment]
Thanks. Do you want me to put your name in the Jamulus About dialog contributers list?

**Comment by stweil** [comment]
> Thanks. Do you want me to put your name in the Jamulus About dialog contributers list?

I don't think that my small contribution is sufficient for that honour. :-)

Many thanks for providing Jamulus. I only recently was informed by a friend of this nice piece of software, and I am really happy how good it works when making music with others. Therefore it is only fair to give something back.

**Comment by corrados** [comment]
I just saw that you are already on the list: https://github.com/corrados/jamulus/blob/master/src/util.cpp#L461
:-)

**Comment by stweil** [comment]
Alla gut, sagt der Kurpfälzer.

**Pull request merged**
