### PR TITLE
Multichannel CoreAudio Support

### PR DESCRIPTION
**Pull request by emlynmac**
The CoreAudio layer to figure out what inputs are available only worked on multiple channels per stream devices.

This PR adds support for the case where _input_ devices have multiple discrete buffers and have need to pull the data out of those buffers properly.

### CODE REVIEW

**Comment by corrados** [comment]
Thanks for your code. I cannot merge your changes directly but will integrate the important changes of the code in the master code of Jamulus as soon as I have a time spot available (very busy right now...).

**Comment by corrados** [comment]
I added the essential changes from your branch to the Git master. Can you please checkout that version and verify that this code works for you?

**Comment by emlynmac** [comment]
Code changes look good visually - will build it and check this evening.
Cheers!

**Comment by emlynmac** [comment]
Confirmed - working with my Phonic Helix FW

**Comment by corrados** [comment]
Great, thank you. I will close this pull request now.

**Comment by corrados** [comment]
Do you have an idea what could go wrong here: https://sourceforge.net/p/llcon/discussion/software/thread/7c443f2ed9/#eeab
It seems your new code introduced the issue for this user.

**Comment by emlynmac** [comment]
Are you still using the same QT / macOS SDK?

I’ve updated to the latest and saw that the CoreAudio callback registration fails _sometimes_. I have no idea yet what is causing it.
Maybe back out the changes I made and see if that resolves the issue for them?

I’ll be digging into why I sometimes get the CoreAudio registration failure sometimes.

**Comment by corrados** [comment]
Yes, the same QT and SDK.
As a quick test I will change to order of the if conditions in callbackIO to see if that helps.
Thanks for your investigations.

**Comment by emlynmac** [comment]
OK perfect.

I also see lots of commits on master :)

Does this mean that 64 samples frame is now in place there?

I’m planning to investigate from master.

And this is Volker, yes?

I’m Emlyn - in Vancouver, BC.

Cheers,

**Comment by corrados** [comment]
Yes, this is Volker and yes, the 64 samples version should now work. I just tried it out with my band mates and it works great.

**Comment by emlynmac** [comment]
Hi,

I’ve had a dig through and I’m consistently seeing the out callback denied by CoreAudio.

I tried separating out the callbacks from one function, which got rid of the error but didn’t get it functional. The error I was seeing was kAudioHardwareIllegalOperationError. Now, I see a different error: 
HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine.


I also found a path I missed - dealing with output with discrete channels. I’ve put a fix for this up at https://github.com/emlynmac/jamulus/tree/fix-out-multichannel

I’m wondering if there’s something happening with core audio not being entirely happy with how it’s being used.

I found some sample code from apple:




This is grabbing audio and then playing out, but it’s using AudioUnits in addition to the AUHal.

I’m wondering if this might be the way to go to make it work.

If I get time, I can have a look at making this work, but got 3 other projects on the go at the moment and a small child :)

E

**Comment by corrados** [comment]
Wow, that took me quite long to figure out what goes wrong...
Can you please test this version: https://sourceforge.net/p/llcon/discussion/software/thread/7c443f2ed9/#b038/04be
if it still runs fine with your sound card?

**Comment by emlynmac** [comment]
I will give it a shot. Is this from the master branch ?

**Comment by corrados** [comment]
Yes, this is from master branch.

**Comment by emlynmac** [comment]
Ah man!

THANK YOU!

I’m glad you found the issue!

This is working great for me, although very strangely, I have to build it with the QT 5.12 toolchain; if I use Xcode, it does not work.

How can I buy you a beer?

Emlyn

**Comment by corrados** [comment]
How about a virtual one: 🍺
:-)

**Comment by emlynmac** [comment]
Cheers! 

🍻

**Comment by corrados** [comment]
I just changed the Mac audio interface to support Aggregated Devices. I had to change a lot of code. Could you try out the latest code on Git master if it still works with your sound card?

**Pull request closed without merging**
