### PR TITLE
Fix server bug causing crash when recording enabled

### PR DESCRIPTION
**Pull request by doloopuntil**
Fix server bug preventing recording directory from being recognised after successful creation.
Small update to compiler flags.
Build tested on Ubuntu.

### CODE REVIEW

**Comment by corrados** [comment]
@pljones can you please review the code since the change is in your code? Thanks.

**Comment by doloopuntil** [comment]
Hi @pljones 
Without this change the server throws a runtime exception _"directory" exists but is not a directory_ when started with _-R "directory"_ to record a session. This happens in the [CJamSession constructor](https://github.com/corrados/jamulus/pull/16/commits/26ccef90fcf9250ae074bdd122371afd07d24156#diff-4432fac68d2a7b10d13cdf41d9081c31L109). The directory is actually [created successfully](https://github.com/corrados/jamulus/pull/16/commits/26ccef90fcf9250ae074bdd122371afd07d24156#diff-4432fac68d2a7b10d13cdf41d9081c31L117), but the QFileInfo object holding the directory state is not updated automatically and [reports the directory as missing](https://github.com/corrados/jamulus/pull/16/commits/26ccef90fcf9250ae074bdd122371afd07d24156#diff-4432fac68d2a7b10d13cdf41d9081c31L121). See also [QFileInfo::setCaching](https://doc.qt.io/qt-5/qfileinfo.html#setCaching).

I'm very happy to rebase on top of master and create a new pull request. This is my very first pull request, so I wasn't sure about the process you prefer to follow. Let me know if you prefer me to do that.

**Comment by pljones** [comment]
> Without this change the server throws a runtime exception _"directory" exists but is not a directory_ when started with _-R "directory"_ to record a session.
Without the change from C++0x to C++11?  That's odd.

**Comment by corrados** [comment]
Thanks guys, I appreciate your help.

**Pull request merged**
